name: CI

on:
  push:
    branches:
      - releases

jobs:
  build:
    name: Build CBCHAIN
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v2

      # PREPARE
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 16

      # BUILD
      - name: Build with Gradle
        run: ./gradlew clean build publish

      - name: Publish Artifact to GIT
        uses: SpinyOwl/publish-artifact-to-git@1.0.0
        with:
          repository: SpinyOwl/repo
          branch: releases
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: build/publish
          no_delete: 'true'
